default:
  dataset: CIFAR100
  dataset_root: ./data
  model: resnet18
  num_classes: 100
  image_size: 32

  shards: 1
  epochs_per_shard: 200
  batch_size: 128

  optim: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  sched: cosine
  min_lr: 1e-5

  enable_watermark: false
  apply_dp_noise: false
