default:
  dataset: ImageNet
  dataset_root: ./data
  model: resnet18
  num_classes: 1000
  image_size: 224

  shards: 4
  epochs_per_shard: 60
  batch_size: 256

  optim: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  sched: cosine
  min_lr: 1e-5

  n_bits: 512
  lambda_w: 0.15
  lambda_w_warmup_epochs: 20
  lambda_w_ramp_epochs: 20
  beta: 0.04
  eta_G: 0.9
  DP_sigma: 5e-5
